
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-09-27 18:55:13.472350
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
AIM_BASEDIR := $(BASEDIR)AIM


ALL_MODULES := $(ALL_MODULES) AIM
